# app.yaml
runtime: nodejs22 # Specifies the Node.js runtime

# This is the default instance class, good for simple apps
instance_class: F1 

# App Engine will automatically look for and run your "start" script
# in package.json. You can also override it with 'entrypoint':
# entrypoint: node server.js
automatic_scaling:
  min_instances: 0
  max_instances: 1